server:
  port: 80
#  servlet:
#    context-path: /Shopme
spring:
  datasource:
    password: Sophie1610
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        formate_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 672231998645-o67km6c08prst3t43hck0rmq52ta3a5a.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 266460375613901
            client-secret: 4d97874319c0e36288d640607150b9a0
            scope:
            - email
            - public_profile
          
